spring.application.name=UserService
server.port=9070

# jwt.secret=${JWT_SECRET}
jwt.secret= #add random secret key

sweetshop.profile.upload.dir=#profile pictures url
sweetshop.profile.default.avatar=#default profile pictures url
sweetshop.sweets.upload.dir=#sweets images url
sweetshop.sweets.default.avatar=#default image url

# SQL Server Configuration
spring.datasource.url=#db url
spring.datasource.username=#username
spring.datasource.password=#password
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# Automatically update schema (optional: update, create, validate, none)
spring.jpa.hibernate.ddl-auto=update
